// MCA Rules Knowledge Base - Winter 2026
// Auto-generated from "One Day (T35) and T20 Rules -- Winter 2026" and
// "Juniors Competition Rules -- Winter 2026"
window.MCA_RULES = [

// ===================== FORMAT (Senior) =====================
{category:"format", keywords:["t35","overs","format","how many overs","one day"], q:"How many overs per side in T35?", a:"T35 is 35 overs per side (unless rain interrupted or wet outfield)."},
{category:"format", keywords:["t35","side change","overs per side","5 overs"], q:"How often do sides change in T35?", a:"5 overs are to be played from each side before a side change."},
{category:"format", keywords:["t35","bowler","max overs","7 overs"], q:"What is the maximum overs a bowler can bowl in T35?", a:"A maximum of 7 overs for any bowler in T35."},
{category:"format", keywords:["t20","overs","format","how many overs"], q:"How many overs per side in T20?", a:"T20 is 20 overs per side (unless rain interrupted or wet outfield)."},
{category:"format", keywords:["t20","bowler","max overs","4 overs"], q:"What is the maximum overs a bowler can bowl in T20?", a:"A maximum of 4 overs for any bowler in T20."},
{category:"format", keywords:["t20","side change","ends","wind"], q:"How often do sides change in T20?", a:"The bowling team changes sides every over until the first 5 overs, then from over 6 onwards changes sides every 5 overs until the end of the game. In a reduced-overs game, sides change every over until the powerplay overs finish, then every 5 overs. This takes advantage of wind conditions during the powerplay."},

// ===================== POWERPLAY (Senior) =====================
{category:"powerplay", keywords:["t35","powerplay","mandatory","bowling powerplay"], q:"What is the T35 powerplay rule?", a:"T35 has a mandatory bowling powerplay of the first 5 overs, plus a batting powerplay of 5 overs that the batting team chooses to take at any point. Total powerplay is 10 overs out of the 35."},
{category:"powerplay", keywords:["t20","powerplay","first 6 overs"], q:"What is the T20 powerplay rule?", a:"T20 has a mandatory powerplay for the first 6 overs."},
{category:"powerplay", keywords:["batting powerplay","choose","when"], q:"When can the batting team take their batting powerplay in T35?", a:"The batting powerplay (5 overs) is up to the batting team to choose any time during their innings, in addition to the mandatory 5-over bowling powerplay."},
{category:"powerplay", keywords:["reduced overs","powerplay table","rain","fewer overs"], q:"How many powerplay overs are there in a reduced-overs T35 game?", a:"It depends on the total overs in the innings: 5-6 overs=1 PP, 7-9=2, 10-13=3, 14-16=4, 17-19=5, 20-22=6, 23-25=7, 26-28=8, 29-31=9, 32-35=10 powerplay overs."},
{category:"powerplay", keywords:["reduced powerplay","split","mandatory batting","odd number"], q:"How are reduced powerplay overs split between mandatory and batting powerplay?", a:"Reduced powerplay overs are shared half each between mandatory and batting powerplay. If the number is odd, it's divided by 2 with the higher number going to the mandatory powerplay. Example: 7 total powerplay overs = 4 mandatory + 3 batting powerplay overs."},

// ===================== FIELDING (Senior) =====================
{category:"fielding", keywords:["fielders outside circle","bowling powerplay","two fielders"], q:"How many fielders can be outside the circle during bowling powerplay?", a:"Only two fielders are allowed outside the inner circle during bowling powerplay overs, regardless of how many players the team has (e.g. even with only 9 players, 2 can field outside the circle)."},
{category:"fielding", keywords:["fielders outside circle","batting powerplay","three fielders"], q:"How many fielders can be outside the circle during batting powerplay?", a:"Only three fielders are allowed outside the inner circle during batting powerplay overs, regardless of team size."},
{category:"fielding", keywords:["fielders outside circle","non-powerplay","five fielders","max fielders"], q:"How many fielders can be outside the circle in non-powerplay overs?", a:"A maximum of 5 fielders are allowed outside the inner circle during non-powerplay overs, regardless of squad size. E.g. with 9 players, 5 can be outside the circle, leaving only 2 fielding inside the circle (excluding keeper and bowler)."},
{category:"fielding", keywords:["leg side fielders","max leg side","five"], q:"What is the maximum number of fielders allowed on the leg side?", a:"A maximum of 5 fielders are allowed on the leg side at any stage of the game (excluding the bowler and keeper)."},
{category:"fielding", keywords:["bowler guard","around the wicket","count as fielder"], q:"Does a bowler's guard position count as a fielder?", a:"No. Bowler guard (e.g. a right-hand bowler bowling around the wicket) doesn't count as a fielder for fielding restriction purposes."},
{category:"fielding", keywords:["9 players","short team","fielding restrictions"], q:"If my team only has 9 players, do fielding circle restrictions still apply?", a:"Yes, the same fielding restrictions apply regardless of squad size (e.g. 9 players) — 2 outside during bowling powerplay, 3 during batting powerplay, 5 during non-powerplay."},

// ===================== COMPETITION (Senior) =====================
{category:"competition", keywords:["league rounds","how many rounds","t35","t20"], q:"How many league rounds are there for regular T35 and T20 grades?", a:"16 league rounds for both T35 and T20, followed by finals."},
{category:"competition", keywords:["finals structure","quarter finals","semi finals","grand final"], q:"What is the finals structure for regular grades?", a:"Depends on number of teams: Quarter Finals (10+ teams), Preliminary Semis (8+ teams), Semi Finals, and Grand Final."},
{category:"competition", keywords:["finals format","ipl","bbl","playoff"], q:"What finals format does MCA use?", a:"Where possible, an IPL/BBL-style playoff: 1st vs 2nd (winner goes straight to Grand Final, loser gets another chance) and 3rd vs 4th (loser eliminated). The two losers/survivors play a qualifier, with the winner joining the Grand Final. May be adjusted based on team numbers and dates."},
{category:"competition", keywords:["reduced t35","10 rounds","league rounds"], q:"How many league rounds in the Reduced T35 fixtured grades?", a:"10 league rounds, followed by finals (Preliminary Semis if more than 6 teams, Semi Finals, and Grand Final)."},
{category:"competition", keywords:["minimum games","qualify finals","6 games"], q:"How many league games must a player play to qualify for finals (regular grades)?", a:"A player must have played a minimum of 6 league games to qualify for Preliminary Semis, Semis and Finals in regular T35/T20 grades."},
{category:"competition", keywords:["minimum games","reduced t35","4 games","qualify"], q:"How many league games must a player play to qualify for finals in Reduced T35?", a:"A player must have played a minimum of 4 league games to qualify for Preliminary Semis, Semis and Finals in Reduced T35 grades."},
{category:"competition", keywords:["match day","saturday","when are matches played"], q:"What day are senior matches played?", a:"All matches are played on Saturday afternoons, except for reserve days."},
{category:"competition", keywords:["multiple teams","same club","grade qualification","two clubs"], q:"If a player plays for multiple teams from the same club, which grade do they qualify for?", a:"A player can play for any team from their club during the season but qualifies for finals only in the one grade where they played the most games. The same rule applies if a player played for two different clubs in the same grade."},

// ===================== GAME-TIMES (Senior) =====================
{category:"game-times", keywords:["t35","toss","time","11:45"], q:"What time is the toss for T35?", a:"The T35 toss is by 11:45 AM. If a team has fewer than 6 players at toss time, the opponent is awarded the toss. If both have fewer than 6, the first team to reach 6 players is awarded the toss."},
{category:"game-times", keywords:["t35","start time","finish time","12pm","2:15","4:45"], q:"What are the T35 innings times?", a:"1st Innings: starts 12 PM, scheduled finish 2:15 PM. Innings break: 15 mins. 2nd Innings: starts 2:30 PM, scheduled finish 4:45 PM. There's a 5-minute drinks break at the end of the 20th over."},
{category:"game-times", keywords:["t20","toss","time","7:45"], q:"What time is the toss for T20?", a:"The T20 toss is by 7:45 AM. If a team has fewer than 6 players at toss time, the opponent is awarded the toss. If both have fewer than 6, the first team to reach 6 players is awarded the toss."},
{category:"game-times", keywords:["t20","start time","finish time","8am","9:30","11:10"], q:"What are the T20 innings times?", a:"1st Innings: starts 8 AM, scheduled finish 9:30 AM. Innings break: 10 mins. 2nd Innings: starts 9:40 AM, scheduled finish 11:10 AM. There's a 5-minute drinks break at the end of the 10th over."},
{category:"game-times", keywords:["minimum players","start game","6 players","fielding team"], q:"What is the minimum number of players to start a senior game?", a:"The fielding team needs a minimum of 6 players to start the game."},
{category:"game-times", keywords:["drinks break","when"], q:"When is the drinks break in senior games?", a:"T35: 5-minute drinks break at the end of the 20th over. T20: 5-minute drinks break at the end of the 10th over."},

// ===================== UMPIRES (Senior) =====================
{category:"umpires", keywords:["how many umpires","league round","one umpire"], q:"How many umpires officiate a senior league round?", a:"One professional umpire will be present for all league rounds."},
{category:"umpires", keywords:["two umpires","finals","semi finals","pre-semis"], q:"How many umpires officiate finals matches?", a:"Two umpires are provided for Pre-Semis (if the fixture has one), Semi-Finals and Finals."},
{category:"umpires", keywords:["pay umpires","finals umpire fee"], q:"Who pays for the two umpires in finals?", a:"Teams have to pay for both umpires in Pre-Semis, Semi-Finals and Finals."},
{category:"umpires", keywords:["umpires decision","final decision","disputes"], q:"Is the umpire's decision final?", a:"Yes, the umpire's decision is final throughout the course of the match. Disputes or complaints must be emailed to the committee within 48 hours of game completion at melbournecricketassociation@gmail.com."},

// ===================== GROUND-SETUP (Senior) =====================
{category:"ground-setup", keywords:["home team","setup","stumps","cones","who sets up"], q:"Who sets up the ground for a senior match?", a:"The home team (listed top on the PlayHQ fixture) sets up stumps and cones for that week."},
{category:"ground-setup", keywords:["home team","supply","scoreboard","balls","first aid","measuring tape"], q:"What does the home team need to supply?", a:"The home team supplies the scoreboard, spare used balls, white spray can, first aid kit, measuring tape, ball counter, and the square leg umpire vest (any orange Hi-Vis vest)."},
{category:"ground-setup", keywords:["clean ground","leave clean"], q:"Does the ground need to be cleaned after the match?", a:"Yes, the home team must ensure the ground is left clean."},

// ===================== TEAM-SHEETS (Senior) =====================
{category:"team-sheets", keywords:["12 players","how many players per side","bat bowl field"], q:"How many players can play per side and what are the batting/bowling/fielding limits?", a:"12 players can play per side. Any 11 of the 12 can bat, any 12 of the 12 can bowl, and any 11 of the 12 can field/wicket keep. All players must be added to the PlayHQ team list before the game starts."},
{category:"team-sheets", keywords:["playhq team list","register before game"], q:"Do all players need to be listed on PlayHQ before the game?", a:"Yes, all players should be added to the PlayHQ team list before the game starts."},
{category:"team-sheets", keywords:["matches locked","wednesday","following week"], q:"When are matches locked on PlayHQ?", a:"All matches are locked on the Wednesday of the following week. Matches can be unlocked if required by the association for valid reasons."},
{category:"team-sheets", keywords:["manual scorebook","no manual books"], q:"Are manual scorebooks allowed?", a:"No manual books are allowed unless there is an issue with the PlayHQ scoring system. All games should be live scored using PlayHQ (https://ca.score.playhq.com)."},

// ===================== DELAYS-RAIN (Senior) =====================
{category:"delays-rain", keywords:["delayed start","wet outfield","4 mins","one over lost"], q:"What happens if the game start is delayed due to weather/wet outfield?", a:"One over is lost for every 4 minutes of delayed start. The umpire reduces the overs equally between both teams."},
{category:"delays-rain", keywords:["rain interruption","60 minutes","called off","points shared"], q:"What happens if there is 60 minutes or more of rain interruption?", a:"If conditions are unsuitable to resume, the game is called off and points are shared. It's up to the umpire's discretion whether to continue during slight drizzle, based on ground/pitch conditions."},
{category:"delays-rain", keywords:["dls","duckworth lewis","when applied"], q:"When does DLS (Duckworth Lewis) come into play?", a:"DLS comes into play if the second innings is interrupted by rain or other weather conditions. The PlayHQ scoring app has DLS built in and should be used. If the app isn't working, the Revised Target rule is used instead."},
{category:"delays-rain", keywords:["slight drizzle","umpire discretion"], q:"Who decides whether play continues during light rain?", a:"It's up to the umpire's discretion whether to continue play during slight drizzle, based on ground and pitch conditions."},

// ===================== BAD-LIGHT (Senior) =====================
{category:"bad-light", keywords:["bad light","t35 only","sunset","applies"], q:"Does the bad light rule apply to T20?", a:"No, the bad light rule currently only applies to T35 due to 'bad light after sunset' concerns."},
{category:"bad-light", keywords:["sunset time","how to check","google"], q:"How do you check the official sunset time?", a:"Search the word 'sunset' on google.com from your mobile — it will show the official sunset time for the day in your local area."},
{category:"bad-light", keywords:["after sunset","no further ball","dls result"], q:"What happens if a game is still going after sunset in T35?", a:"No further ball can be bowled beyond the official sunset time. The result will be based on DLS. Teams should not stop for bad light before official sunset — the umpire decides if light is too gloomy before then, and may direct only spinners to bowl."},
{category:"bad-light", keywords:["batting powerplay","bad light","spinners"], q:"Can the batting powerplay still be taken during bad light conditions?", a:"Yes, the batting powerplay can still be taken during bad light. The bowling team shouldn't object to bowling spinners or the batting powerplay once the umpire has made the final call."},

// ===================== REDUCED-OVERS (Senior) =====================
{category:"reduced-overs", keywords:["reduced overs","delayed start","t35 only","4 mins"], q:"How are overs reduced for a delayed start in T35?", a:"An over is reduced for every 4 minutes of delay past the 5-minute grace period beyond the scheduled 12:00 PM start time."},
{category:"reduced-overs", keywords:["delayed finish","first innings","chasing team overs"], q:"What happens if the first innings finishes late?", a:"If the team bowling first has a delayed finish, when they come to bat they get reduced overs (one over reduced per 4 minutes past 2:15 PM), but the target to chase remains the same. If the team fielding second finishes late (past scheduled finish/sunset), DLS applies instead."},
{category:"reduced-overs", keywords:["over rate","15 overs per hour","warning"], q:"What over rate are teams expected to maintain in T35?", a:"Umpires warn teams throughout the game if behind on over rate. Generally, 15 overs per hour is expected with a mix of pace and spin bowlers."},
{category:"reduced-overs", keywords:["forfeit","12:30pm","6 players","t35"], q:"What happens if a T35 team doesn't have 6 players by 12:30 PM?", a:"That team is considered a forfeit. A team must start the game as soon as there are 6 players in the ground. Penalties may apply for teams turning up late on multiple occasions."},

// ===================== REVISED-TARGET (Senior) =====================
{category:"revised-target", keywords:["revised target","how calculated","run rate","example"], q:"How is the revised target calculated if PlayHQ DLS isn't working?", a:"The revised target = revised overs x first innings run rate. Example: Team A scores 175 in 35 overs (run rate 5/over). If the 2nd innings is rain-reduced to 15 overs, the revised target is 15 x 5 = 75 runs."},
{category:"revised-target", keywords:["minimum overs","result","5 overs","draw"], q:"What is the minimum overs needed for a result?", a:"A minimum of 5 overs must be played in either the first or second innings for a result. Otherwise the game is considered a draw."},
{category:"revised-target", keywords:["washed out","abandoned","complete washout"], q:"What happens if a game is completely washed out?", a:"If the complete game is washed out, it is considered abandoned and match points are shared between both teams."},
{category:"revised-target", keywords:["points","win","draw","6 points","3 points"], q:"How many points for a win or draw?", a:"A win earns 6 points. A draw earns 3 points each. Draw or abandoned games have points shared between both teams."},

// ===================== FREE-HIT (Senior) =====================
{category:"free-hit", keywords:["free hit","when awarded","no-ball","waist height"], q:"When is a free hit awarded in senior cricket?", a:"A free hit applies for every no-ball — waist height, over-stepping, ball landing outside the mat, above shoulder/head short balls, etc."},
{category:"free-hit", keywords:["second short ball","shoulder","same over","no-ball"], q:"What happens on a second short ball above the shoulder in the same over?", a:"The second short ball above the shoulder in the same over is called a no-ball (and results in a free hit)."},
{category:"free-hit", keywords:["bowler","non-striker","stumps","mankad"], q:"Is it a no-ball if the bowler disturbs the stumps at the non-striker's end?", a:"Yes, a bowler disturbing the stumps at the non-striker end while bowling is considered a no-ball."},
{category:"free-hit", keywords:["who calls no-ball","square leg","main umpire"], q:"Who makes the final call on no-balls?", a:"All no-ball calls, including waist-high no-balls, are made by the official/main umpire, who may consult the square leg umpire if in doubt, but the final call rests with the main umpire."},

// ===================== SQUARE-LEG (Senior) =====================
{category:"square-leg", keywords:["orange vest","ball counter","who provides"], q:"Who provides the square leg umpire's vest and ball counter?", a:"All teams must provide an Orange Hi-Vis vest and ball counter for their square leg umpires."},
{category:"square-leg", keywords:["reset stumps","broken","keeper end"], q:"Who resets the stumps if broken at the keeper's end?", a:"The square leg umpire is required to reset the stumps when broken at the keeper's end."},
{category:"square-leg", keywords:["talk to batters","interact","5-run penalty"], q:"Can square leg umpires talk to batters?", a:"No. Square leg umpires must not interact or speak with batters during overs, between overs, or at the fall of a wicket. A 5-run penalty is awarded against the batting team if observed, and the umpire will be rotated off square leg duties."},
{category:"square-leg", keywords:["mobile phone","drink bottle","square leg","penalty"], q:"Can square leg umpires carry a mobile phone or drink bottle?", a:"No, square leg umpires must not carry mobile phones or drink bottles. A 5-run penalty applies against the batting team if observed, and they'll be rotated off square leg duties. A quick drink is allowed at the change of ends or fall of a wicket."},

// ===================== WIDES (Senior) =====================
{category:"wides", keywords:["t35","leg side wide","one warning","warning per over"], q:"What is the leg-side wide rule for T35?", a:"One warning per over for a ball down the leg side (unless too far, which is an immediate wide without warning). Anything after the warning is a wide. If the first ball down leg was called a wide (too far), the next down-leg ball is treated as the warning if it isn't too far."},
{category:"wides", keywords:["last ball of over","leg side","t35","wide"], q:"Is the last ball of the over down leg side always a wide in T35?", a:"Yes, the last ball of any over bowled down leg side is called a wide in T35."},
{category:"wides", keywords:["t20","leg side wide","any ball"], q:"What is the leg-side wide rule for T20?", a:"In T20, any ball down the leg side is considered a wide — there is no warning."},
{category:"wides", keywords:["free hit","leg side","wide","moved to next delivery"], q:"What happens if a free hit delivery goes down the leg side?", a:"Any ball bowled down leg side on a free hit delivery is called a wide, and the free hit carries over to the next delivery."},

// ===================== CARDS-DISCIPLINE (Senior) =====================
{category:"cards-discipline", keywords:["yellow card","report","email board"], q:"What happens when a player is issued a yellow card?", a:"The umpire must report the player and incident details to the board via email, by the following Sunday evening at the latest."},
{category:"cards-discipline", keywords:["two yellow cards","same game","disqualified"], q:"What happens if a player gets two yellow cards in the same game?", a:"The player is disqualified from playing for the rest of that game and cannot be replaced for the remainder of the game."},
{category:"cards-discipline", keywords:["three yellow cards","season","suspension"], q:"What happens if a player gets three yellow cards during the season?", a:"An automatic suspension of one game applies. Any further yellow cards during the season incur a further one-match suspension each."},
{category:"cards-discipline", keywords:["card carryover","next season","deducted"], q:"Do yellow cards carry over to the next season?", a:"One card is deducted from the tally for the following season. E.g. a player with 2 yellow cards has 1 deducted, leaving 1 remaining for the following season."},
{category:"cards-discipline", keywords:["red card","two card offence","disciplinary"], q:"What happens with red card or two-yellow-card reports?", a:"The board investigates two-yellow-card or red-card reports and proceeds with disciplinary action."},

// ===================== ATTIRE (Senior) =====================
{category:"attire", keywords:["uniform","team attire","hoodie","jumper"], q:"What are the uniform requirements for senior teams?", a:"All teams must have uniforms, including the same hoodie/jumper/jacket. Full team must wear the same uniform (full whites or full club colours) — no mix matching. Teams must carry spares for last-minute fill-ins."},
{category:"attire", keywords:["whites only","no coloured uniform"], q:"What if a team doesn't have coloured uniforms?", a:"Teams without coloured uniforms must be dressed in whites only. Any coloured or white uniform is fine as long as all team members wear the same one."},
{category:"attire", keywords:["mixed uniforms","different clubs"], q:"Are mixed uniforms from different clubs allowed?", a:"No, mixed uniforms from different clubs are not allowed."},
{category:"attire", keywords:["uniform penalty","5 runs deducted"], q:"What is the penalty for not having proper uniform?", a:"5 runs are deducted from the team's score for each player that doesn't have proper uniform."},
{category:"attire", keywords:["bowler","black top","sighting concerns","white clothing"], q:"Can a batsman request a bowler to change clothing for sighting concerns?", a:"Yes. If the fielding team wears white and the batsman on strike has sighting concerns, they can ask the umpire for the bowler of that over to wear a black top (t-shirt/jumper/hoody). Only black is permitted, and teams should carry spares."},

// ===================== REPORTS (Senior) =====================
{category:"reports", keywords:["umpire report","match report","deadline","sunday evening"], q:"When must umpires submit their match report?", a:"Umpires must provide a match report by Sunday evening at the latest, to give ongoing feedback to the committee."},
{category:"reports", keywords:["captain report","optional"], q:"Do captains need to submit a match day report?", a:"Captains can optionally provide a match day report by Sunday evening at the latest, or email the association directly for any match day matters."},
{category:"reports", keywords:["match result","manual entry","10pm","playhq not working"], q:"What happens if PlayHQ live scoring isn't working during the match?", a:"The home team must enter match results manually by 10 PM the following day."},

// ===================== FEES (Senior) =====================
{category:"fees", keywords:["fees","how much","flyer"], q:"Where can I find the competition fees?", a:"Fees are as advised in the competition flyers."},
{category:"fees", keywords:["bank details","bsb","account number","payment"], q:"What are the MCA bank details for fee payment?", a:"Name: MCA. BSB: 063106. Account number: 10904465. Reference: use your team's name as per the PlayHQ fixture."},
{category:"fees", keywords:["umpire fee","t35","$85"], q:"What is the umpire fee for T35?", a:"$85 per team, paid in full if the game starts. If called off before the first ball, half payment is due. If the association calls off the game before 11 AM on game day, no umpire fee is payable."},
{category:"fees", keywords:["umpire fee","t20","$65"], q:"What is the umpire fee for T20?", a:"$65 per team, paid in full if the game starts. If called off before the first ball, half payment is due. If the association calls off the game the previous night, no umpire fee is payable."},
{category:"fees", keywords:["when pay umpire","before toss","payid"], q:"When should umpire fees be paid?", a:"Umpire payments should be paid before the toss, either online (PayID or bank transfer)."},

// ===================== BALLS (Senior) =====================
{category:"balls", keywords:["ball","kookaburra","cost","$30","hoppers crossing"], q:"What ball is used and where can I buy it?", a:"Ask for the MCA Kookaburra Crown 2-piece white ball ($30 a ball), an association-specific ball with a logo, from Hoppers Crossing Cricket Store (03) 9369 5410 or another nearby sports shop."},
{category:"balls", keywords:["ball colour","durability","change ball"], q:"Could the match ball change during the season?", a:"MCA will assess ball colour and durability through the season and may change or trial other branded balls for a few rounds if needed."},

// ===================== NO-BALLS (Senior) =====================
{category:"no-balls", keywords:["no-ball","waist height","above waist"], q:"What counts as a no-ball for height?", a:"Any ball above the batsman's waist (without pitching) is a no-ball, regardless of bowler type (spin, medium, or pace)."},
{category:"no-balls", keywords:["beamer","above shoulder","two beamers"], q:"What happens if a bowler bowls a beamer?", a:"A ball above the shoulder without pitching is a beamer. If a bowler bowls two beamers in the course of the game, they cannot continue bowling for the rest of the game."},

// ===================== OVER-RATE (Senior) =====================
{category:"over-rate", keywords:["slow over rate","umpire reminder"], q:"Is there a blanket rule for slow over rates?", a:"No blanket rule, but the umpire keeps an eye on over rate and reminds the fielding team if they're running behind (general guide is 15 overs per hour)."},

// ===================== LATE-PLAYERS (Senior) =====================
{category:"late-players", keywords:["players arriving late","can they bat bowl"], q:"Can a player who arrives late still bat or bowl?", a:"Yes, no restrictions apply — they can bowl or bat any time. This is subject to the rule that a player shouldn't be playing two games in the same time slot (i.e. late arrival must not be from another game)."},

// ===================== ABUSE (Senior) =====================
{category:"abuse", keywords:["personal comments","racist","abuse policy"], q:"What is MCA's policy on abuse or racist comments?", a:"No personal or racist comments will be tolerated, and no abuse will be tolerated. Any physical abuse or fight involving a team results in strict action."},

// ===================== FIELDERS-CALL (Senior) =====================
{category:"fielders-call", keywords:["fielder's call","boundary","cone"], q:"What is the fielder's call rule for boundaries?", a:"Fielder's call is accepted for boundaries, unless the umpire clearly sees the fielder go over or touch a cone. Where there is no cone in the fielded area, fielder's call stays."},

// ===================== BOWLING-ACTION (Senior) =====================
{category:"bowling-action", keywords:["suspect bowling action","chucking","object"], q:"Can a team stop a bowler for a suspected illegal bowling action?", a:"No, a batsman or team shouldn't stop a bowler for a suspected action. Instead the objecting team's square leg umpire may record a clip of the over (after notifying the main umpire, who notifies the bowler) and send it to the association for review."},
{category:"bowling-action", keywords:["video recording","notify umpire"], q:"Can I record video of a bowler's action without telling the umpire?", a:"No, videos should not be recorded without notifying the umpire first."},
{category:"bowling-action", keywords:["chucking confirmed","cricket victoria","training"], q:"What happens if a bowler is confirmed to be chucking?", a:"The association may advise the player to attend a training session at Cricket Victoria to rectify their bowling action."},

// ===================== AWARDS (Senior) =====================
{category:"awards", keywords:["awards","best bowler","best batsman","man of the match"], q:"What awards are given in the One Day competition?", a:"Best Bowler, Best Batsman, Best Fielder, Best Keeper of the tournament, Most 6s (T20), Man of the Match every game (including finals), medals/trophies for winners and runners-up, a Championship trophy, and a Finals Umpire trophy."},
{category:"awards", keywords:["championship trophy","runner up","medals"], q:"Do all players get medals?", a:"Yes, all players in the winning team receive medals and trophies, and all players in the runner-up team receive medals."},

// ===================== STREAMING (Senior) =====================
{category:"streaming", keywords:["frogbox","youtube","live streaming","senior"], q:"Are senior games live streamed?", a:"Some games are live streamed through FrogBox on the PlayHQ app and YouTube channels. Umpires allow extra time to fix streaming issues, and all clubs/teams are assumed to accept the associated privacy laws."},

// ===================== SCORING (Senior) =====================
{category:"scoring", keywords:["playhq","online scoring","mandatory","no exceptions"], q:"Is online scoring mandatory?", a:"Yes, all games must be scored online through the PlayHQ website on a phone or tablet — no exceptions. Umpires allow extra time to fix technology issues."},

// ===================== LOST-BALL (Senior) =====================
{category:"lost-ball", keywords:["lost ball","replace","old ball"], q:"What happens if a ball is lost during play?", a:"Replace it with an old used ball from a previous game. The umpire will agree on the replacement ball's condition."},

// ===================== FORFEITS (Senior) =====================
{category:"forfeits", keywords:["forfeit","notify","thursday 8pm","senior"], q:"What is the deadline to notify a forfeit for a senior game?", a:"If you don't have enough players and can't play that week's game, notify the opponent team and the association by Thursday before 8 PM."},

// ===================== COVID (Senior) =====================
{category:"covid", keywords:["covid","kit sharing","saliva","waste bins"], q:"What are MCA's COVID rules?", a:"No kit or food sharing, no saliva on the ball, and all waste must go into bins."},

// ===================== PLAYHQ (Senior/general) =====================
{category:"playhq", keywords:["playhq links","creating team","game permit","live score guide"], q:"Where can I find PlayHQ help guides?", a:"PlayHQ support articles cover Creating a Team, Selecting Team/Line-Ups, Adding/Replacing Fill-in Players, How to Live Score, Electronic Scoring guides, and Creating a Game Permit Request — see the PlayHQ Links section of the rules document, or the PlayHQ Support Request page for other issues."},
{category:"playhq", keywords:["fill in player","add replace","playhq"], q:"How do I add or replace a fill-in player on PlayHQ?", a:"Use PlayHQ's 'Managing Fill-in Players via Admin Portal' guide, accessible from the PlayHQ Links section of the rules document."},

// ===================== REGISTRATION (Senior) =====================
{category:"registration", keywords:["player registration","playhq registered"], q:"Do all players need to be registered on PlayHQ?", a:"Yes, all players should be registered on PlayHQ."},
{category:"registration", keywords:["two teams","same day","same tournament"], q:"Can a registered player play for two teams in the same tournament on the same day?", a:"No, a registered player cannot play for two teams in the same tournament on the same day."},
{category:"registration", keywords:["transfer","permit","difference"], q:"What's the difference between a Transfer and a Permit?", a:"A player wishing to play for another team in the same fixture needs a Transfer, not a Permit. If both teams are from the same club, neither Transfer nor Permit is required."},
{category:"registration", keywords:["fill in","game permit","registered","playhq fill in"], q:"What are the rules for fill-in players?", a:"A team can use as many fill-ins as needed as long as rules are followed. Fill-ins must be registered or added via the 'game permit' option for a one-off game or while awaiting permit/transfer approval. If a player has never played using their PlayHQ ID, they can be used as a 'PlayHQ Fill In' for their first game only — from the second game onwards they must be fully registered."},
{category:"registration", keywords:["captain responsibility","check eligibility"], q:"Whose responsibility is it to check player eligibility?", a:"It's the captain's responsibility to check whether a player has already played for another team in the same fixture. Non-compliance can result in the association awarding points to the losing team or deducting points from the ladder."},

// ===================== RESERVE-DAYS (Senior) =====================
{category:"reserve-days", keywords:["reserve days","which games","league washed out"], q:"Do league games get a reserve day if washed out?", a:"No. If a league game is washed out by rain, there is no reserve day and points are shared. Only Preliminary Semis, Semi Finals and Grand Finals have reserve days."},
{category:"reserve-days", keywords:["semi final washed out","reserve day","ladder top"], q:"What happens if a Pre-Semi or Semi Final is washed out even on the reserve day?", a:"The team that finished on top of the ladder goes through to the next stage."},
{category:"reserve-days", keywords:["grand final washed out","reserve day","championship"], q:"What happens if the Grand Final is washed out on the reserve day too?", a:"The team that finished on top of the ladder is awarded the championship."},

// ===================== GENERAL (Senior contacts) =====================
{category:"general", keywords:["committee","president","secretary","treasurer","contact"], q:"Who is on the MCA Association Committee?", a:"President: Gopi Kakivai (0430 667 896). Secretary: Mahendra Annem (0433 960 586). Treasurer: Sandeep Shamala (0433 249 914). Umpires Coordinator: Srikanth Dendi (0430 408 093). You may contact any of them for queries."},
{category:"general", keywords:["disputes","complaints","48 hours","email"], q:"How do I lodge a dispute or complaint?", a:"Email melbournecricketassociation@gmail.com within 48 hours of the game's completion."},
{category:"general", keywords:["other rules","international rules","laws of cricket"], q:"What rules apply where the MCA rule book doesn't specify something?", a:"International cricket rules (Laws of Cricket) apply in general where not exclusively specified in the MCA rule book."},

// ===================== JUNIORS - GENERAL =====================
{category:"juniors-general", keywords:["season start","juniors","26 april"], q:"When does the juniors season start?", a:"The juniors season starts 26 April 2026."},
{category:"juniors-general", keywords:["match days","juniors","alternate sundays"], q:"What days are junior matches played?", a:"Junior matches (U11, U13, U15) are played on alternate Sundays, starting 12:30 PM."},
{category:"juniors-general", keywords:["start time","juniors","12:30"], q:"What time do junior matches start?", a:"All junior grades (U11, U13, U15) have a scheduled start time of 12:30 PM."},
{category:"juniors-general", keywords:["dispensation","request","age","5pm thursday"], q:"How do I request a dispensation for a junior player?", a:"Email melbournecricketassociation@gmail.com by 5 PM the Thursday before the game, including the player's name, date of birth, and grade requested."},
{category:"juniors-general", keywords:["points system","juniors","playhq"], q:"How are points allocated in juniors?", a:"Points are allocated as per PlayHQ's standard points system for all junior grades."},
{category:"juniors-general", keywords:["finals qualification","top 4","juniors"], q:"How many teams qualify for junior finals?", a:"The top 4 teams qualify for finals in all junior grades (U11, U13, U15)."},
{category:"juniors-general", keywords:["minimum games","finals","juniors","3 games"], q:"How many league games must a junior player play to qualify for finals?", a:"A minimum of 3 league games, across U11, U13, and U15."},
{category:"juniors-general", keywords:["finals format","juniors","playhq standard","double chance"], q:"What finals format is used for juniors?", a:"PlayHQ Standard finals format, giving a double chance for the 1st and 2nd placed teams."},
{category:"juniors-general", keywords:["forfeit notice","juniors","saturday 6pm"], q:"By when must a junior team give forfeit notice?", a:"By Saturday 6:00 PM, the day before the match."},
{category:"juniors-general", keywords:["forfeit consequences","fine","withdrawn","30 minutes"], q:"What happens if a junior team forfeits a match?", a:"A team unable to field the grade minimum within 30 minutes of scheduled start forfeits. The forfeiting team gets no points; the opponent gets a maximum-points result. The forfeiting team is liable for the full umpire fees for both sides. Late notice (after Saturday 6 PM) or a no-show incurs a fine on top of umpire fees. Forfeiting three matches in a season means the team is deemed withdrawn from the competition."},
{category:"juniors-general", keywords:["home team responsibilities","juniors","crease lines","boundary markers"], q:"What must the home club prepare for a junior match?", a:"By start time: clearly marked crease lines, boundary markers per age-group dimensions, inner-circle markers (U13/U15), stumps and bails set up, scorers' table and chairs, clubroom/toilet access where possible, ground mowed with a playable pitch, and sprinklers turned off the night before. Both teams must leave the ground in good order afterward."},
{category:"juniors-general", keywords:["springback stumps","mandatory","u11","u13"], q:"Are springback stumps mandatory for juniors?", a:"Yes, mandatory for U11 and U13. With springback stumps, the stumps are deemed broken if the ball strikes them (other than the metal base), even if the bails don't dislodge."},
{category:"juniors-general", keywords:["ball replacement","juniors","lost ball","unfit"], q:"What happens if the ball is lost or becomes unfit during a junior match?", a:"The umpire replaces it with a ball of comparable wear and informs both batters and the fielding captain at the time of replacement."},
{category:"juniors-general", keywords:["coach on field","field placements","juniors"], q:"Can a coach be on the field during a junior match?", a:"Yes, a coach or assistant coach may assist the captain with field placements during play, provided it doesn't delay the game and isn't used to coach the batter or distract opponents."},
{category:"juniors-general", keywords:["pitch surface","synthetic","turf"], q:"Are junior matches played on turf or synthetic pitches?", a:"All MCA matches are played on synthetic pitches — MCA does not play on turf wickets."},
{category:"juniors-general", keywords:["substitute","loan players","sub fielder"], q:"What are the rules for loan and substitute players in juniors?", a:"Loan players (when one team is short and the opposition has surplus) are strongly encouraged, may bat/bowl/field, and their figures count for the team they're loaned to. Substitute fielders (for illness/injury) may only field — not bat, bowl or keep — max 2 on field at once, and must be flagged to the opposition coach and umpire and be PlayHQ-registered."},
{category:"juniors-general", keywords:["finals eligibility","3 home and away","juniors"], q:"What are the finals eligibility rules for junior players?", a:"A player must have played a minimum of 3 home-and-away matches for that team during the season, and played more games for that team than for any other team in the same age group. Active participation means having batted, bowled, or fielded. The MCA Committee may grant exceptions in extenuating circumstances on written application 48 hours before the match."},
{category:"juniors-general", keywords:["toss","juniors","15 minutes before"], q:"When is the toss conducted for junior matches?", a:"At least 15 minutes before the scheduled start of play, provided both teams have the minimum number of players present. A team without the grade minimum 15 minutes before start forfeits the toss."},
{category:"juniors-general", keywords:["fill ins","juniors","exact registered name"], q:"How are fill-ins handled in juniors if a transfer/permit hasn't completed?", a:"The player may take the field as a Fill In for that match, entered in PlayHQ using their exact registered name. Once the transfer/permit is finalised (typically by the following Thursday), the Fill In entry must be replaced with the player's actual PlayHQ profile."},
{category:"juniors-general", keywords:["rules version","v0.4"], q:"What version are the current junior rules?", a:"The Juniors Competition Rules (Winter 2026) are version v0.4, dated 10/05/2026."},

// ===================== JUNIORS - U11 =====================
{category:"juniors-u11", keywords:["u11","overs","format","25 overs"], q:"How many overs per side in U11?", a:"25 overs per side."},
{category:"juniors-general", keywords:["age group","which grade","what grade","my child","age","which age group","u11 u13 u15","dob"], q:"What age group is my child in?", a:"Age is taken as at 26 April 2026. U11: 8 to 11 years (born 27 April 2014 to 26 April 2018). U13: 9 to 13 years (born 27 April 2012 to 26 April 2017). U15: 12 to 15 years (born 27 April 2010 to 26 April 2014). The bands overlap, so some children are eligible for two grades — clubs place them by age and ability."},
{category:"juniors-u11", keywords:["u11","age range","dob","8 to 11"], q:"What age group is U11 for?", a:"Ages 8 to 11 years on 26 April 2026. DOB window: 27 April 2014 to 26 April 2018."},
{category:"juniors-u11", keywords:["u11","ball","pink","kooka soft"], q:"What ball is used in U11?", a:"Kooka Soft Pink ball, 130g."},
{category:"juniors-u11", keywords:["u11","umpire fee","$65"], q:"What is the umpire fee for U11?", a:"$65 per team."},
{category:"juniors-u11", keywords:["u11","pitch length","players","boundary"], q:"What are the pitch, player and boundary settings for U11?", a:"Pitch length: 16m. Ideal players per team: 7 (min 5, max 11). Max players on field: 7. Boundary: 40m from centre of pitch. No inner circle in U11."},
{category:"juniors-u11", keywords:["u11","retirement","balls per batter","formula"], q:"How does batter retirement work in U11?", a:"Balls per batter = total balls in innings ÷ number of players (rounded down): 5 players=30 balls, 6=25, 7=21, 8=18, 9=16, 10=15, 11=13 balls. All deliveries including wides/no-balls count. A batter must retire immediately on reaching their allocation. For U11, if balls don't divide evenly, the last batsman (nominated by the team manager/coach) faces the remaining balls."},
{category:"juniors-u11", keywords:["u11","dismissal","unlimited","4 run penalty"], q:"How do dismissals work in U11?", a:"Unlimited dismissals — all batters face their full ball allocation and the innings ends when allocated overs are bowled; retired/dismissed batters don't return. A dismissal penalty of 4 runs is added to the fielding team's total for every dismissal."},
{category:"juniors-u11", keywords:["u11","lbw","allowed"], q:"Is LBW allowed in U11?", a:"No, LBW is not applicable in U11."},
{category:"juniors-u11", keywords:["u11","safety zone","15m","fielder distance"], q:"How close can fielders stand to the batter in U11?", a:"No fielder may stand closer than 15m to the batter (wicketkeeper excepted). There is no powerplay or inner circle in U11."},
{category:"juniors-u11", keywords:["u11","3 bounce","no ball","ball delivery rule"], q:"What is the 3-bounce rule in U11?", a:"A delivery that bounces three or more times before reaching the batter's crease is called a no-ball (U11 only). Max 6 balls per over, and all deliveries including wides/no-balls count."},

// ===================== JUNIORS - U13 =====================
{category:"juniors-u13", keywords:["u13","overs","format","25 overs"], q:"How many overs per side in U13?", a:"25 overs per side."},
{category:"juniors-u13", keywords:["u13","age range","dob","9 to 13"], q:"What age group is U13 for?", a:"Ages 9 to 13 years on 26 April 2026. DOB window: 27 April 2012 to 26 April 2017."},
{category:"juniors-u13", keywords:["u13","ball","white 2 piece","142g"], q:"What ball is used in U13?", a:"MCA Stamped Kooka Crown White 2 Piece ball, 142g."},
{category:"juniors-u13", keywords:["u13","umpire fee","$65"], q:"What is the umpire fee for U13?", a:"$65 per team."},
{category:"juniors-u13", keywords:["u13","pitch length","inner circle","boundary","players"], q:"What are the pitch, boundary and player settings for U13?", a:"Pitch length: 18m. Boundary: 45m from centre of pitch. Inner circle: 20m. Ideal players: 9 (min 7, max 11). Max players on field: 9."},
{category:"juniors-u13", keywords:["u13","wicket cap","innings ends"], q:"How many wickets end a U13 innings?", a:"The innings ends when the wicket cap by team size is reached, or all allocated overs are bowled, whichever comes first: 7 players=6 wickets, 8=7, 9=8, 10=8, 11=9 wickets."},
{category:"juniors-u13", keywords:["u13","lbw","allowed"], q:"Is LBW allowed in U13?", a:"No, LBW is not applicable in U13."},
{category:"juniors-u13", keywords:["u13","powerplay","bowling","batting","8 overs"], q:"What is the powerplay in U13?", a:"Bowling powerplay: first 4 overs, max 2 fielders outside the 20m circle. Batting powerplay: 4 overs of the batting team's choice, max 3 fielders outside the circle. Total powerplay: 8 overs per innings."},
{category:"juniors-u13", keywords:["u13","non-powerplay","fielders outside circle","max 4"], q:"How many fielders can be outside the circle in U13 non-powerplay overs?", a:"Maximum 4 fielders outside the inner circle in non-powerplay overs."},
{category:"juniors-u13", keywords:["u13","safety zone","10m","fielder distance"], q:"How close can fielders stand to the batter in U13?", a:"No fielder may stand closer than 10m to the batter (wicketkeeper and slips excepted)."},
{category:"juniors-u13", keywords:["u13","retirement","balls per batter","formula"], q:"How does batter retirement work in U13?", a:"Same formula as U11: balls per batter = total balls in innings ÷ number of players (rounded down). Unlike U11, U13 has no nominated last batsman — the innings runs to its allocated overs unless the wicket cap is reached first, and any unused per-batter allocation lapses with a dismissed batter."},
{category:"juniors-u13", keywords:["u13","dismissal penalty","none"], q:"Is there a dismissal penalty in U13?", a:"No, unlike U11, there is no dismissal penalty in U13 — a dismissed batter is simply out and does not return, with no runs added to the fielding team's total."},
{category:"juniors-u13", keywords:["u13","retired not out","return","wicket cap"], q:"Can a retired batter return to bat in U13?", a:"Yes, a batter who retires not out returns to bat at the fall of the last available wicket (once wicket-cap-minus-one is reached) and continues until dismissed or the innings ends. Multiple retired batters return in order of retirement."},

// ===================== JUNIORS - U15 =====================
{category:"juniors-u15", keywords:["u15","overs","format","30 overs"], q:"How many overs per side in U15?", a:"30 overs per side."},
{category:"juniors-u15", keywords:["u15","age range","dob","12 to 15"], q:"What age group is U15 for?", a:"Ages 12 to 15 years on 26 April 2026. DOB window: 27 April 2010 to 26 April 2014."},
{category:"juniors-u15", keywords:["u15","ball","white 2 piece","156g"], q:"What ball is used in U15?", a:"MCA Stamped Kooka Crown White 2 Piece ball, 156g."},
{category:"juniors-u15", keywords:["u15","umpire fee","$70"], q:"What is the umpire fee for U15?", a:"$70 per team."},
{category:"juniors-u15", keywords:["u15","pitch length","full size","boundary","inner circle"], q:"What are the pitch, boundary and player settings for U15?", a:"Pitch length: 20m (full size). Boundary: 55m from centre of pitch. Inner circle: 25m. Ideal players: 11 (min 7, max 13). Max players on field: 11."},
{category:"juniors-u15", keywords:["u15","wickets","10 wickets","end innings"], q:"How many wickets end a U15 innings?", a:"10 wickets, like standard cricket."},
{category:"juniors-u15", keywords:["u15","lbw","allowed"], q:"Is LBW allowed in U15?", a:"Yes, LBW applies in U15 (the only junior grade where it applies)."},
{category:"juniors-u15", keywords:["u15","retirement","50 runs","return"], q:"How does batter retirement work in U15?", a:"Batters retire after scoring 50 runs. Retired batters may return at the fall of the last available wicket and continue batting until dismissed or the innings ends."},
{category:"juniors-u15", keywords:["u15","powerplay","10 overs","bowling batting"], q:"What is the powerplay in U15?", a:"Bowling powerplay: first 5 overs, max 2 fielders outside the 25m circle. Batting powerplay: 5 overs of the batting team's choice, max 3 fielders outside the circle. Total powerplay: 10 overs per innings. Non-powerplay: max 5 fielders outside the circle."},
{category:"juniors-u15", keywords:["u15","free hit","every no-ball"], q:"Is there a free hit in U15?", a:"Yes, U15 is the only junior grade with a free hit, awarded for every no-ball (overstepping, waist height, above shoulder/head, ball outside mat, etc). On a free hit, the batter can only be dismissed by run-out, hit ball twice, or obstructing the field."},
{category:"juniors-u15", keywords:["u15","leg side wide","one warning"], q:"What is the leg-side wide rule in U15?", a:"One warning per over for a leg-side ball (unless clearly too far, which is an immediate wide). After the warning, any subsequent leg-side ball in that over is a wide. The last ball of any over down leg side is always an immediate wide, and a leg-side free hit ball is a wide with the free hit carrying over."},
{category:"juniors-u15", keywords:["u15","max balls per over","8 balls","6 legal"], q:"How many balls per over in U15?", a:"Max 8 balls per over (6 legal deliveries are required to complete the over)."},
{category:"juniors-u15", keywords:["u15","max overs per bowler","6 overs","min 6 bowlers"], q:"What are the bowling limits in U15?", a:"Max 6 overs per bowler, minimum 6 bowlers must be used per innings. Wicketkeepers are not mandated to bowl."},
{category:"juniors-u15", keywords:["u15","leg side fielders","max 5"], q:"What is the max leg-side fielders in U15?", a:"Maximum 5 fielders on the leg side at any time (excluding bowler and keeper), same as senior rules."},
{category:"juniors-u15", keywords:["u15","end changes","5 overs"], q:"How often do bowling ends change in U15?", a:"End changes occur every 5 overs throughout the innings."},

// ===================== JUNIORS - GENERAL TIMES/RAIN/DLS =====================
{category:"juniors-general", keywords:["juniors","hours of play","cut off time","2:10","2:30"], q:"What are the innings cut-off times for junior matches?", a:"First innings cut-off: 2:10 PM (U11 & U13) or 2:30 PM (U15) — the over in progress is completed. Innings break is 10 minutes. Second innings/scheduled finish cut-off: 4:20 PM (U11 & U13) or 5:00 PM (U15). Overs caps remain 25 (U11/U13) and 30 (U15)."},
{category:"delays-rain", keywords:["juniors","delayed start","4 minutes","forfeit 1pm"], q:"What happens if a junior match start is delayed?", a:"One over is deducted from each innings for every 4 minutes of delayed start past 12:30 PM, reduced equally by the umpire. A team must start once the grade minimum is present (U11:5, U13:7, U15:7). If the grade minimum isn't reached by 1:00 PM, that team forfeits."},
{category:"delays-rain", keywords:["juniors","rain interruption","60 minutes"], q:"What is the rain interruption rule for juniors?", a:"A cumulative rain interruption of 60 minutes or more, if conditions are unsuitable to resume, means the game is called off and points are shared. Shorter interruptions are at the umpire's discretion."},
{category:"revised-target", keywords:["juniors","dls","revised target","example"], q:"How is DLS/revised target applied in junior matches?", a:"DLS applies when the second innings is rain-interrupted, using the PlayHQ scoring app. If unavailable, revised target = revised overs x first innings run rate. Example: Team A scores 100 in 25 overs (run rate 4.0); if the second innings is revised to 15 overs, the target is 15 x 4.0 = 60 runs."},
{category:"revised-target", keywords:["juniors","minimum overs","draw","abandoned"], q:"What is the minimum overs for a result in junior matches?", a:"5 overs must be completed by each team for a result to stand. If not achieved it's a draw with points shared equally. A full washout with no play is an abandoned match with points shared."},
{category:"bad-light", keywords:["juniors","u15 only","bad light","sunset"], q:"Does the bad light rule apply to junior grades?", a:"Only U15. Play continues until official sunset (search 'sunset' on Google). No ball may be bowled after sunset. Before sunset, if light is poor, the umpire may direct only spinners to bowl; the batting team may still take their powerplay and the bowling team cannot object. Shortened games are decided by DLS."},
{category:"over-rate", keywords:["juniors","over rate","15 overs per hour"], q:"What over rate is expected in junior matches?", a:"Approximately 15 overs per hour. Umpires warn teams falling behind, and persistent delays may result in penalties at the association's discretion."},
{category:"square-leg", keywords:["juniors","square leg umpire","batting team provides"], q:"Who provides the square leg umpire in junior matches?", a:"The square-leg umpire is provided by the batting team for each innings."},

// ===================== JUNIORS - BATTING =====================
{category:"juniors-batting", keywords:["u11 u13","retirement example","7 players","21 balls"], q:"Can you give an example of batter retirement allocation in U11/U13?", a:"With a 7-player team: 21 balls per batter x 7 = 147 of 150 total balls, leaving 3 balls unallocated. In U11 the nominated last batsman faces those extra balls. In U13 there's no nominated last batsman — the innings just runs to its allocated overs or the wicket cap, whichever comes first."},
{category:"juniors-batting", keywords:["balls counted","wides no balls","retirement"], q:"Do wides and no-balls count toward a batter's retirement ball count?", a:"Yes, all deliveries including wides and no-balls count toward a batter's ball allocation in U11/U13, and the batter must retire immediately on reaching it — not at the end of the over."},
{category:"juniors-batting", keywords:["u15","batter retirement","50 runs","return order"], q:"What happens after a U15 batter retires at 50 runs?", a:"They may return to bat at the fall of the last available wicket and continue until dismissed or the innings ends."},

// ===================== JUNIORS - BOWLING =====================
{category:"juniors-bowling", keywords:["bowling order rule","u11 u13","2 overs before 3rd"], q:"What is the bowling order rule in U11 and U13?", a:"All players, including the wicketkeeper, must bowl 2 overs each before any bowler bowls a 3rd over, and must bowl 3 overs each before any bowler bowls a 4th over."},
{category:"juniors-bowling", keywords:["max overs per bowler","juniors","by age"], q:"What is the max overs per bowler in each junior grade?", a:"U11 and U13: max 5 overs per bowler. U15: max 6 overs per bowler."},
{category:"juniors-bowling", keywords:["all players must bowl","u11","u13"], q:"Must every player bowl in U11/U13?", a:"Yes, all players must bowl in U11 and U13 (subject to the bowling order rule and 5-over cap)."},
{category:"juniors-bowling", keywords:["u15","min bowlers","wicketkeeper not mandated"], q:"How many bowlers must be used in U15?", a:"Minimum 6 bowlers must be used per innings; wicketkeepers are not mandated to bowl. There's no restriction on bowling order beyond the max 6 overs per bowler."},

// ===================== JUNIORS - SAFETY =====================
{category:"juniors-safety", keywords:["helmets","mandatory","batters keepers"], q:"Are helmets mandatory for junior batters and keepers?", a:"Yes, an approved helmet with visor/grille is mandatory for all batters and wicketkeepers in every junior age group at all times while batting or wicketkeeping. If a keeper isn't wearing one, the umpire stops play until they comply."},
{category:"juniors-safety", keywords:["working with children check","wwc","coaches","videographers"], q:"Who needs a Working with Children Check?", a:"All coaches, assistant coaches, team managers, regular training staff, scorers who interact with players, and any videographers/video editors must hold a current Working with Children Check. Clubs must keep a copy on file."},
{category:"juniors-safety", keywords:["first aid kit","requirements","contents"], q:"What must be in a team's first aid kit?", a:"Every team must carry a first aid kit with bandages, cotton wool, gauze, adhesive plaster/Band-Aids, wound closures, scissors, tweezers, antiseptic, disposable gloves, disposable plastic bags, and an ice pack. Failure to provide one on request may result in a fine."},
{category:"juniors-safety", keywords:["sun safety","sunsmart","hats","5 litre"], q:"What is the sun safety policy for juniors?", a:"Clubs follow the SunSmart policy: wide-brimmed hats must be available as an option (in addition to caps), three-quarter or long-sleeved shirts are preferred, and each team must have a 5-litre drinks container at every match."},
{category:"juniors-safety", keywords:["child safety officer","complaints manager","deepak"], q:"Who is the Child Safety Officer?", a:"Deepak Kulkarni is the Child Safety Officer and Complaints Manager (0404 073 222, deepak7kulkarni@gmail.com), also the Juniors Coordinator."},
{category:"juniors-safety", keywords:["insurance","registration","playhq","public liability"], q:"How are junior players insured?", a:"All players must be registered on PlayHQ, which is the players' insurance vehicle. Each club is separately responsible for its own public liability insurance."},
{category:"juniors-safety", keywords:["proof of age","birth certificate","new players"], q:"Do new junior players need to provide proof of age?", a:"Yes, all new players must provide a copy of their birth certificate (or other suitable proof of age) to the club at registration, and the club must keep it on file."},
{category:"juniors-safety", keywords:["alcohol","forbidden","junior match"], q:"Is alcohol allowed at junior matches?", a:"No, alcohol consumption is forbidden in or in visible proximity to a junior match, before, during, or immediately after the game."},
{category:"juniors-safety", keywords:["suspect bowling action","juniors","no no-ball call"], q:"How are suspect bowling actions handled in juniors?", a:"No umpire calls a no-ball for a suspect action on the field. Concerns should be raised quietly with the bowler's coach after the match and reported to the Juniors Coordinator, who contacts the player's club. The player must not be ostracised or publicly called out; repeated concerns may see them barred from bowling until the club shows the action is corrected."},
{category:"juniors-safety", keywords:["policy adoption","cricket australia","safeguarding children"], q:"What child safety policies does MCA follow?", a:"MCA adopts Cricket Australia's Policy for Safeguarding Children and Young People, Cricket Australia's 'Looking After Our Kids' Code of Behaviour, Cricket Victoria's Member Protection Policy, and Cricket Victoria's Reporting and Complaints Policy. All clubs, coaches, players, parents and officials are bound by these and the MCA Code of Behaviour."},

// ===================== JUNIORS - STREAMING =====================
{category:"juniors-streaming", keywords:["live streaming","optional","frogbox","juniors"], q:"Is live streaming of junior matches required?", a:"No, it's optional. Clubs choosing to stream must comply with all requirements, including under-18 consent."},
{category:"juniors-streaming", keywords:["consent","under 18","frogbox go","72 hours"], q:"What consent is needed to stream a junior match?", a:"Clubs must confirm consent in FrogBox Go for any under-18 participants within 72 hours of the scheduled match start time."},
{category:"juniors-streaming", keywords:["access streams","youtube link","play cricket app"], q:"How is junior stream access controlled?", a:"Junior streams are accessible via an unlisted YouTube link shared by the hosting club. Once under-18 consent is confirmed, streams and highlights also appear in the Play Cricket app, where access is restricted to consented under-18 participants to protect privacy."},
{category:"juniors-streaming", keywords:["complaints","content removal","footage"], q:"How do I request removal of streamed footage?", a:"Email melbournecricketassociation@gmail.com. Footage subject to a valid complaint will be promptly removed from all online platforms. All videographers/editors must hold a current Working with Children Check and agree in writing that footage is only used for approved purposes."},

// ===================== JUNIORS - SCORING =====================
{category:"scoring", keywords:["juniors","live scoring","mandatory","nominated scorer"], q:"Is live scoring mandatory for junior matches?", a:"Yes, PlayHQ Live Scoring is mandatory — no manual scorebooks. The scorer is nominated by the batting team for that innings (any nominated person — player, parent, or official)."},

// ===================== JUNIORS - CODE OF BEHAVIOUR / DISPUTES =====================
{category:"general", keywords:["spirit of cricket","sledging","send-offs","dissent"], q:"What is expected under the Spirit of Cricket for juniors?", a:"All matches are played in the Spirit of Cricket. Players, coaches, parents and spectators must respect umpires, opponents, and each other. Sledging, send-offs, dissent, abuse of officials, and conduct contrary to the Cricket Victoria Member Protection Policy are reportable."},
{category:"general", keywords:["reporting breach","code of behaviour","juniors","48 hours"], q:"How do I report a breach of the Code of Behaviour in juniors?", a:"Report to melbournecricketassociation@gmail.com within 48 hours of game completion, including match details, people involved, and nature of the alleged breach."},
{category:"general", keywords:["dispute resolution","committee decision","7 days"], q:"How does MCA resolve disputes?", a:"The MCA Committee reviews the report, may seek further evidence, and issues a written decision within 7 days. The Committee may reprimand, fine, suspend, or impose other penalties. Committee decisions are final."},
{category:"general", keywords:["juniors coordinator","deepak kulkarni","contact"], q:"Who is the Juniors Coordinator?", a:"Deepak Kulkarni (0404 073 222, deepak7kulkarni@gmail.com) is the Juniors Coordinator (and also the Child Safety Officer)."},

];
